### PR TITLE
Biopax additional attributes

### PR DESCRIPTION
**Pull request by metincansiper**
Work together with https://github.com/PathwayCommons/factoid-converters/pull/11
Refs #724 and #737

I have a Factoid dcument where the only ineracion is represented by ``egf interacts with egf``. For that document the following biopax template is created to enable the data exchange with the biopax converter.

```
{"interactions":[{"type":"Other Interaction","participants":[{"type":"ggp","name":"egf","xref":{"db":"MIM","id":"131530"},"organism":{"id":"9606","db":"taxonomy"}},{"type":"ggp","name":"egf","xref":{"db":"MIM","id":"131530"},"organism":{"id":"9606","db":"taxonomy"}}]}],"publication":{"id":"32483207","db":"pubmed"}}
```

Then biopax converter exports the following content.

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:owl="http://www.w3.org/2002/07/owl#"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
 xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#">
<owl:Ontology rdf:about="">
 <owl:imports rdf:resource="http://www.biopax.org/release/biopax-level3.owl#" />
</owl:Ontology>

<bp:UnificationXref rdf:about="c91247c2-b37c-49c7-8d9c-45a535e351f6">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">9606</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">taxonomy</bp:db>
</bp:UnificationXref>

<bp:PublicationXref rdf:about="ad7e4209-b125-43ad-ae8f-869c5297c278">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">32483207</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">pubmed</bp:db>
</bp:PublicationXref>

<bp:Pathway rdf:about="303278b4-e74f-49d2-b545-cc8676c35eb8">
 <bp:pathwayComponent rdf:resource="27b2f2a7-d987-4a6f-9e5b-14c16b569e85" />
 <bp:xref rdf:resource="ad7e4209-b125-43ad-ae8f-869c5297c278" />
</bp:Pathway>

<bp:Protein rdf:about="031080e1-fc5c-4c7d-a7c5-77e2180d3dde">
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">egf</bp:displayName>
 <bp:entityReference rdf:resource="f43778cb-cf5d-41bf-b8e2-d2b259a6873a" />
</bp:Protein>

<bp:Interaction rdf:about="27b2f2a7-d987-4a6f-9e5b-14c16b569e85">
 <bp:participant rdf:resource="031080e1-fc5c-4c7d-a7c5-77e2180d3dde" />
</bp:Interaction>

<bp:BioSource rdf:about="b6993892-e147-492e-9b88-2bfec59463e0">
 <bp:xref rdf:resource="c91247c2-b37c-49c7-8d9c-45a535e351f6" />
</bp:BioSource>

<bp:ProteinReference rdf:about="f43778cb-cf5d-41bf-b8e2-d2b259a6873a">
 <bp:xref rdf:resource="303e89ba-71e4-4641-bc27-1feffd20c843" />
 <bp:organism rdf:resource="b6993892-e147-492e-9b88-2bfec59463e0" />
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">egf</bp:displayName>
</bp:ProteinReference>

<bp:RelationshipXref rdf:about="303e89ba-71e4-4641-bc27-1feffd20c843">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">131530</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MIM</bp:db>
</bp:RelationshipXref>
</rdf:RDF>
```

For the same model the groovy script of @cannin returns the following sif content:

```
urn:miriam:chebi:15422	used-to-produce	urn:miriam:chebi:16761
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:P06493
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:P36507
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:Q02750
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01111
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01112
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01116
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P04049
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P31946
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P36507
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P05231
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P05231
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P08887
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P08887
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P08887
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P08887
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P06493	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:P06493	controls-phosphorylation-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P06493	controls-state-change-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P06493	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P23458	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P23458	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P27361	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P27361	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P28482	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P28482	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P29597	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P29597	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P29597	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P29597	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P31946	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P31946	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P31946	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P31946	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01111
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P28482
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P36507	controls-phosphorylation-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-transport-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P40189	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P40189	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:Q02750	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01111
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P27361
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:Q02750	controls-phosphorylation-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:Q02750	controls-transport-of	urn:miriam:uniprot:P36507
```

Newt renders the sif file as the following where topology grouping is enabled

Screen Shot 2020-06-09 at 2 00 12 PM

### CODE REVIEW

**Comment by cannin** [comment]
@metincansiper is it valid?

**Comment by metincansiper** [comment]
Travis is failing with the message of ``The command "sudo service rethinkdb start" failed and exited with 5 during .``

**Comment by jvwong** [comment]
Yes, I've seen the travis fails before. Ignore for now assuming you're tests pass locally

**Comment by metincansiper** [comment]
>@metincansiper is it valid BioPAX? Any errors? What does the input factoid look like?

There is no error, there are some warnings:
- WARNING: no.display.name , category: RECOMMENDATION, cases: 3, not fixed: 
**Refers to Pathway, Biosource and Interaction so I think it would be normal.**
- WARNING: no.unification.xref
**I remember talking about this in the past and we ended up with using the RelationshipXref instead.**
-WARNING: range.violated
BioPAX property range violation (illegal value type)
object: 6b54391b-7a59-44df-bd65-8ecda13c8dd9
property: xref, value: 8f70d397-2888-40fa-bd16-64d9c5f0996d; RelationshipXrefImpl is not UnificationXref
(found by: org.biopax.validator.rules.BioSourceTaxonXrefCRRule)

**This is also related to Xref type. Should we use UnificationXref in general?**

-WARNING: unknown.db 
Unknown database identifier. For Xref 'db' property and Provenance standard/display name properties, please use the official database names from MIRIAM. PSI-MI "database citation" and child terms are also allowed but they are deprecated. Please use MIRIAM when possible
object: 2cdb1c0b-7c4c-4581-b22f-09a8e6215acb
db name: ncbi
(found by: org.biopax.validator.rules.XrefRule)

**I just use the db name as is. Should we use MIRIAM for the official names either in factoid side or in the converter?**

**Comment by metincansiper** [comment]
>What does the input factoid look like?

As I mentioned in description the factoid document only has one interaction in it which is: ``egf interacts with egf``.

And the template to represent it is:

```
{"interactions":[{"type":"Other Interaction","participants":[{"type":"ggp","name":"egf","xref":{"id":"1950","db":"ncbi"},"organism":{"id":"9606","db":"taxonomy"}},{"type":"ggp","name":"egf","xref":{"id":"1950","db":"ncbi"},"organism":{"id":"9606","db":"taxonomy"}}]}],"publication":{"id":"32483207","db":"pubmed"}}
```

**Comment by cannin** [comment]
> > What does the input factoid look like?
> 
> As I mentioned in description the factoid document only has one interaction in it which is: `egf interacts with egf`.
> 
> And the template to represent it is:
> 
> ```
> {"interactions":[{"type":"Other Interaction","participants":[{"type":"ggp","name":"egf","xref":{"id":"1950","db":"ncbi"},"organism":{"id":"9606","db":"taxonomy"}},{"type":"ggp","name":"egf","xref":{"id":"1950","db":"ncbi"},"organism":{"id":"9606","db":"taxonomy"}}]}],"publication":{"id":"32483207","db":"pubmed"}}
> ```

@metincansiper I see. When I saw all the SIF interactions I thought there was more to the Factoid. I see also sorts of complexes and chemicals where are they coming from in the conversion?

**Comment by jvwong** [comment]
> I just use the db name as is. Should we use MIRIAM for the official names either in factoid side or in the converter?

That `ncbi` namespace makes its way from the grounding service, which probably shoulda used the namespace value `ncbigene`.

**Comment by cannin** [comment]
> > @metincansiper is it valid BioPAX? Any errors? What does the input factoid look like?
> 
> There is no error, there are some warnings:
> 
> * WARNING: no.display.name , category: RECOMMENDATION, cases: 3, not fixed:
>   **Refers to Pathway, Biosource and Interaction so I think it would be normal.**
> * WARNING: no.unification.xref
>   **I remember talking about this in the past and we ended up with using the RelationshipXref instead.**
>   -WARNING: range.violated
>   BioPAX property range violation (illegal value type)
>   object: 6b54391b-7a59-44df-bd65-8ecda13c8dd9
>   property: xref, value: 8f70d397-2888-40fa-bd16-64d9c5f0996d; RelationshipXrefImpl is not UnificationXref
>   (found by: org.biopax.validator.rules.BioSourceTaxonXrefCRRule)
> 
> **This is also related to Xref type. Should we use UnificationXref in general?**
> 
> -WARNING: unknown.db
> Unknown database identifier. For Xref 'db' property and Provenance standard/display name properties, please use the official database names from MIRIAM. PSI-MI "database citation" and child terms are also allowed but they are deprecated. Please use MIRIAM when possible
> object: 2cdb1c0b-7c4c-4581-b22f-09a8e6215acb
> db name: ncbi
> (found by: org.biopax.validator.rules.XrefRule)
> 
> **I just use the db name as is. Should we use MIRIAM for the official names either in factoid side or in the converter?**

@metincansiper: 
* Not sure what Factoid is using. Can you ask Emek about MIRIAM? I've seen some people stay with MIRIAM because that's what's their software supports while others are switching to identifiers.org. I would stick with one of these "standards" within the Factoid code (or something very easily convertible). It'll most likely prevent issues later on for users. 
* To my knowledge it isn't so much a question of "generally use" UnificationXRefs. If the ID "is" (exactly matches) the molecule being presented then use Unification. If it is "related" (e.g., HGNC gene ID for a protein where a Uniprot ID would actually be best) then it is RelationshipXref. I thought the grounding was meant to be exact matches. I guess ignore this point from me if Gary/Emek/Igor told you differently.

**Comment by metincansiper** [comment]
>That ncbi namespace makes its way from the grounding service, which probably shoulda used the namespace value ncbigene.

@jvwong the problem was because I used "https://grounding.baderlab.org" again. After switrching to "https://master.grounding.baderlab.org" the problem is fixed for me. An example xref is ``"xref":{"db":"MIM","id":"131530"}``. 

I am currently checking if there is any dbXref available. I guess it will eventually be available in "https://grounding.baderlab.org" as it is in "https://master.grounding.baderlab.org". Until that happens I am not removing that check. I think we can remove it when dbXrefs are available in "https://grounding.baderlab.org" as well.

**Comment by metincansiper** [comment]
>Not sure what Factoid is using. Can you ask Emek about MIRIAM? I've seen some people stay with MIRIAM because that's what's their software supports while others are switching to identifiers.org. I would stick with one of these "standards" within the Factoid code (or something very easily convertible). It'll most likely prevent issues later on for users.

@cannin I think this problem is caused by that I used the wrong url for the grounding service. I beleive that dbXrefs fild must solve this problem (you can see my comment above).

**Comment by metincansiper** [comment]
>To my knowledge it isn't so much a question of "generally use" UnificationXRefs. If the ID "is" (exactly matches) the molecule being presented then use Unification. If it is "related" (e.g., HGNC gene ID for a protein where a Uniprot ID would actually be best) then it is RelationshipXref. I thought the grounding was meant to be exact matches. I guess ignore this point from me if Gary/Emek/Igor told you differently.

The old discussion about that is available in https://github.com/PathwayCommons/factoid/pull/284. 

At the end what Igor told is:


>Sure, use unification xref if it’s a ProteinReference and UniProt ID (or SmallMoleculeReference and ChEBI/PubChem ID) case, but be careful in other cases, because unification xref means identity (and in an ideal world, DnaReference cannot have the same db:id unification xref as some ProteinReference or Gene has, etc.)

I experimented and see that if I use the UnificationXref for the Biosource then the range.violated warning is cleared.

If I use the UnificationXref for the protein reference in my example as below:

```
<bp:UnificationXref rdf:about="a452fef5-b5db-46d2-8508-23190002e606">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">131530</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">MIM</bp:db>
</bp:UnificationXref>
```

then it gives denied.xref warning by saying "Database value of the UnificationXref (of a BioPAX element) does not apply (prohibited) for this type of element". 

If I try to use the UnificationXref with a vaild uniprot xref then all the xref related warnings are gone.

Based on these I think:

- We should switch to UnificationXref for Biosources.
- We may switch to UnificationXref for only some choosen namespaces (uniprot for proteins, for chemicals? anything else for proteins?). For the others we can keep using relationshipxrefs. In this case we see no.unification.xref warning only when we cannot use unificationxref.
- Or for the sake of simplicity we may keep using relationshipxref for any enitity reference. In this case we will not get rid of no.unification.xref warning at all.

Does anyone have any idea or preference?

**Comment by metincansiper** [comment]
I included the updates for #737 as well in this PR.

**Comment by metincansiper** [comment]
I made some updates to use  UnificationXref for Biosources so one of the warnings is completely gone. Entities are still using the relationshipxrefs. I can make some updates for using UnificationXref for entities conditionally if desired.

**Comment by jvwong** [comment]
I don't believe the name/displayName for the bp:Pathway is present? This would probably come from the doc.citation().title

**Comment by maxkfranz** [comment]
@metincansiper & @jvwong -- After resolving some Biopax related issues over email, is this ready to be merged?

If the package-lock.json conflict is difficult to resolve, just delete the file and use the one from unstable.  You can `npm i` again after that to make sure any new packages are there.

**Comment by metincansiper** [comment]
>I don't believe the name/displayName for the bp:Pathway is present? This would probably come from the doc.citation().title

@jvwong if it is the publication of the article would not I just set it as the title of the publicatioxref? Or maybe I assign it to both name of the pathway and title of publicationxref?

**Comment by jvwong** [comment]
> > I don't believe the name/displayName for the bp:Pathway is present? This would probably come from the doc.citation().title
> 
> @jvwong if it is the title of the article would not I just set it as the title of the publicatioxref? Or maybe I assign it to both name of the pathway and title of publicationxref?

You can do both, but at least set the `bp:Pathway` name.

**Comment by metincansiper** [comment]
>You can do both, but at least set the bp:Pathway name.

@jvwong okay I just included bp:Pathway name as you originally suggested. I can add it as publication title as well if specifically desired.

**Comment by jvwong** [comment]
Some conflicts to resolve but looks good to me.

**Comment by jvwong** [comment]
The merge button is disabled because of the conflict

**Comment by metincansiper** [comment]
I resolved the conflict and merged this PR.

**Pull request merged**
