### PR TITLE
Exploring at the network-level: Related Interactions

### PR DESCRIPTION
**Pull request by jvwong**
This is a prototype. Displays more detail of INDRA search results upon interacting with elements of the network in our Explorer.

The original motivation for this feature was to provide more explicit information about why the papers were being displayed for a given network element.

- Notes
  - It is backwards compatible in the sense that it displays 'There were no interactions found for the selected item' for `element.relatedPapers` data with the existing schema, or if in fact none were found
  - 'Show more articles' isn't implemented, not sure if this should be punted til later and how it should be implemented (routing?)
  - I'm showing 'Source' (e.g. Pathway Commons; Human Protein Reference Database) when available but not sure if this is worth including or how to include it  (link to PC apps?).

Refs #937

### CODE REVIEW

**Review by metincansiper — APPROVED** [review]

**Comment by maxkfranz** [comment]
@jvwong, would you merge this in and link to a live example of the results on the unstable instance?

The code looks OK, and I'd like to have a live example to point to in order to comment on the UI.

**Comment by jvwong** [comment]
OKey, I'll put in on master.factoid.baderlab.org - ping you when its done

**Comment by jvwong** [comment]
@maxkfranz  I updated the site, and kicked off an example: https://master.factoid.baderlab.org/document/e5dc3eef-6af0-4c61-8a42-ddeb4a4285b5

**Comment by maxkfranz** [comment]
Looks good.  Minor feedback:

- It would be nice if there were just a bit of spacing between the title, author list, and journal name.  It's close, making it a bit harder to make things out.
- The journal name wouldn't blend in so much with the author list if it were italicised.

**Comment by jvwong** [comment]
We've tries to mitigate failures and provide fall-backs upon 
 - retrieving network related papers from INDRA (#785, #780) 
 - refreshing papers metadata post-submission (#985)

Another existing issue is that when semantic-search returns an error, for whatever reason (https://github.com/PathwayCommons/semantic-search/issues/98) there is no reasonable fallback herein, which ultimately leads to no related papers - its 'all or none'. 

All of these points of failure should be considered in this PR since the relevant code is being updated.

**Pull request closed without merging**
