### PR TITLE
Search UI on the home page

### PR DESCRIPTION
**Pull request by maxkfranz**
- Integrated with the home page.  No looking around to find another page or waiting for a new page to load.
- Shows all docs when search box is focussed and empty.  You can just scroll through the list.
- Shows top 10 search results when you type a query.
- Fixes DocumentSearch returning unsubmitted docs.
- Carousels can be refreshed to be used in search.  May be useful in future for categorised search results.

Ref. :

- Browsing: Beyond the carousel #863
- A class for client-side Document search #984

### CODE REVIEW

**Comment by maxkfranz** [comment]
@jvwong, would you make sure that this is on a public instance for demonstration tomorrow?

**Comment by jvwong** [comment]
Hey this looks great. I had a couple of initial thoughts:

- When I first loaded the page it was difficult to find the search feature, I guess most people have the magnifying glass icon which helps
- When you are searching and clear the text with the (x) icon, the page is empty. The alternative is to go back to browse mode.

I noticed a bug on mobile where the clicking the close (x) shifts the input over rather than close:

**Comment by maxkfranz** [comment]
Let's leave this in a branch until we finalise the search strategy

**Comment by jvwong** [comment]
This branch is useful in the admin, at the very least. I've been coming up with some ridiculously long and complicated Rethinkdb queries to achieve what this is going so maybe at least I will try to incorporate this into the admin.

**Comment by maxkfranz** [comment]
How about we merge this in as-is for now?  We can disable the homepage search before putting this on prod if we want.

**Comment by jvwong** [comment]
This one now has most of the missing pieces. This makes me think that #909 is worth taking a stab at whether we use this or not publically.

**Comment by jvwong** [comment]
FYI I have the latest version of this branch (merged with #909) up on https://test.biofactoid.org/ which auto-builds a Docker image based on the `test` branch.

**Comment by maxkfranz** [comment]
OK, I think it's good to merge

**Pull request merged**
