### PR TITLE
Use a special shortening method for displaying synonyms

### PR DESCRIPTION
**Pull request by metincansiper**
Implemented the second solution for displaying long number of synonyms from issue #202

### CODE REVIEW

**Comment by metincansiper** [comment]
I just realized that I will need to update this PR because memoizing the results of comparison function will not be enough. I need to memoize the distances between synonyms and the search text instead.

**Comment by maxkfranz** [comment]
> I need to memoize the distances between synonyms and the search text instead.

Yes, you need a memoized version of `distanceMetric()` rather than `cmp()`.

**Comment by metincansiper** [comment]
I updated it

**Comment by maxkfranz** [comment]
That's great.  It would be a bit better to remove the `shortenSynonyms()` from `render()` entirely and instead add `ent.shortenSynonyms` inside `updateMatches()`.  It's good practice to keep `render()` as cheap and simple as possible since it can be called many times.

`updateMatches()`, on the other hand, is called only when needed.

**Comment by metincansiper** [comment]
I got it. I renamed ```shortenSynonyms()``` as ```getShortSynonyms()``` (I thought my previous naming would be confusing because shorten would imply directly changing synonyms array) then I moved it to ```updateMatches()``` to calculate ```match.shortSynonyms```. Then inside ```render()``` directly used ```match.shortSynonyms```.

**Comment by maxkfranz** [comment]
It looks good.  The only thing I'd change (re. code organisation) at this point would be to move the distance metric definition to util so that it's defined only in one place.  Right now, if the server changes its string distance metric, the UI would be out of sync.

I'll try running the code on my machine tomorrow, if possible, and then I'll merge.

**Comment by maxkfranz** [comment]
Something like `util.stringDistanceMetric()`

**Comment by metincansiper** [comment]
I totally agree but seems like none of the existing files under ```util``` is suitable to put such a function and I will need to create a new file for this purpose. What could be a good name for the new file? It would be dependent on whether any similar functionalities would be added to that file later. 

I think if the file will not have a more general purpose then we can give it the name of this function that is  ```stringDistanceMetric.js```. However, otherwise it would be dependent on what will be expected from the functions inside the new file.

**Comment by maxkfranz** [comment]
Maybe `strings.js` for string util functions.  We have some formatting stuff for entity data, for example, that could also go there eventually.

**Comment by metincansiper** [comment]
Okay, I introduced new function inside ```strings.js``` and used it from both client and server sides.

**Comment by maxkfranz** [comment]
Great.  I'll merge a bit later today.

**Comment by sacdallago** [comment]
Just checking: can this be merged @maxkfranz ? :)

**Comment by maxkfranz** [comment]
I've got a lot on my plate, so I can't always test a PR right away.  In future after I've reviewed the code itself, you're welcome to test PR to make sure (1) that the code changes are effective and (2) the main usecase isn't broken (i.e. textmining to doc, create a node and ground it, create an edge and add arrows).

**Pull request merged**
