### PR TITLE
Merge synch-fix into unstable

### PR DESCRIPTION
**Pull request by maxkfranz**
Now that the synch-fix branch has addressed the major bugs for the form, it can be merged into unstable.  Note: We may need to make other minor tweaks to unstable before merging it into master.

### CODE REVIEW

**Comment by metincansiper** [comment]
I suppose this line would be mistakenly changed (https://github.com/PathwayCommons/factoid/pull/318/files#diff-9dda8de488fff0af36dc34c46be6738eR47) because it basically assigns ``this.data = this.data = {..}``

**Comment by maxkfranz** [comment]
It's probably just a refactoring tool oversight.  It shouldn't break anything, because it's meaningless to assign to itself.

**Comment by maxkfranz** [comment]
@metincansiper @d2fong I tested on my machine that things work.  It would be great if you would test (even just quickly) to make sure that it's working on your machines.

```
git fetch origin
git checkout -b synch-fix origin/synch-fix
git merge unstable
npm install
npm run watch
```

**Comment by metincansiper** [comment]
I tried by merging sync-fix into unstable. It worked fine for me. I just found out one thing but I am not sure if it is something worths considering. If you have an interaction on network editor whose tooltip is active and try to change activates/inhibits status of it from the form editor tooltip in network editor does not update itself.

**Comment by d2fong** [comment]
I tried it on my machine.  I didn't notice any issues.

**Comment by maxkfranz** [comment]
@metincansiper I tried and I wasn't able to reproduce that on my machine.  Let's merge and then take it from there, as it's not a major issue.

**Comment by maxkfranz** [comment]
OK, unstable.factoid.baderlab.org should reflect the changes in the next 15-30 minutes.

**Comment by sacdallago** [comment]
I was just able to test it out now, but it all builds and from a simple example it all looks good to me. I guess interesting will be the extensive testing over the next two days on the unstable remote

**Pull request merged**
