### PR TITLE
Cron system: Update Article metadata

### PR DESCRIPTION
**Pull request by jvwong**
Introduces a CRON system for updating the article metadata from Pubmed.

- General
  - CRON system is scheduled via config variable `CRON_SCHEDULE` to trigger updates provided to it  
- Document updates implemented 
  - article metadata (PubMed)
    - Documents to update are filtered based upon
      - Not the DEMO
      - Status not 'trashed'       
      - Missing values for doi or pmid 
      - Optional config `DOCUMENT_CRON_CREATED_AGE_DAYS` to filter out those created more than this many days ago (seems like acceptance to publication timeline is ~1-2 months)

Refs #729

### CODE REVIEW

**Comment by maxkfranz** [comment]
One quick piece of feedbacks is that we may want to update docs even if they have an existing pmid. Updating old data may be useful in addition to filling in kissing data

**Comment by jvwong** [comment]
> One quick piece of feedbacks is that we may want to update docs even if they have an existing pmid. Updating old data may be useful in addition to filling in kissing data

Definite over-optimisation at this point (nothing to update currently).

**Comment by jvwong** [comment]
Maybe a better solution is a config flag: `DOCUMENT_CRON_REFRESH_ARTICLE` or something to indicate that it should include docs with data.

**Comment by maxkfranz** [comment]
I agree that refreshes of prior hits may be too early to consider for this
PR, but refreshing existing hits will become more important when it's
considered it in tandem with related papers cron jobs.

Many of these cron-job-style refreshes may be a bit of an over-optimisation
for the general homepage user flow.  As a prospective user, why would I
create a shareable summary of my paper if I can't yet actually share the
link to my paper itself?  The timing and incentives are off.

It's still good to think about refreshes, and it may be useful in some
cases (e.g. enthusiastic authors who take action on the Cell acceptance
letter blurb).  Having config values and flags to toggle these cron
features would be good.  If we decide, for example, that we don't need it
enabled right away, then we can switch it off temporarily with the config
flag.

**Comment by jvwong** [comment]
While we're here, I added a flag `DOCUMENT_CRON_REFRESH_ENABLED` that toggles the refresh of Document metadata.

Right now, everything that is not demo or trashed gets updated.

**Comment by jvwong** [comment]
Travis is failing because of rethinkdb install on VM, not the code.

**Comment by maxkfranz** [comment]
﻿I think we disabled the travis unit tests because travis was flakey with rethinkdb.  It may make sense to just remove all the rehinkdb stuff from the travis config completely if we keep getting false errors

**Pull request merged**
