### PR TITLE
UI tweaks and fixes

### PR DESCRIPTION
**Pull request by maxkfranz**
- Makes several tweaks to the network editor & form
- See commit titles for list of changes
- See screenshots below for summary

screen shot 2018-06-22 at 3 17 31 pm

screen shot 2018-06-22 at 3 17 41 pm

screen shot 2018-06-22 at 3 23 46 pm

See #319

### CODE REVIEW

**Comment by d2fong** [comment]
Looks fine to me but putting the form button types in a popover would lead to users having to click twice to create an interaction in comparison to the old way.

**Comment by metincansiper** [comment]
Looks fine to me. However there is only one thing confusing me. In the latest edit of [interaction types table of #297](https://github.com/PathwayCommons/factoid/issues/297#issuecomment-394846756) any participant combinations other than Protein-Protein is removed from general interaction type of factoid.

screen shot 2018-06-22 at 4 36 24 pm

However, after this PR factoid still supports other combinations of Protein and Chemical under general interaction type. Therefore, there would be an inconsistency about that.

**Comment by metincansiper** [comment]
Other than that I would propose to have some icons to represent template types and adding them to the left-most of template interaction lines in the form editor (would have content made up from names of template types e.g. "PM" for protein modification). 

Not sure if it looks nice but I am proposing in case you want to consider since having such icons would make distinguishing between different types of templates easier.

**Comment by maxkfranz** [comment]
> any participant combinations other than Protein-Protein is removed from general interaction type of factoid.

The editor selects the type automatically for P*C.  Basically, the list is simplified to indicate only the types that the UI guides the user to use.  A user could manually select the general type (or even the wrong type).  The convertor would have to handle these edgecases either by inferring a more correct type or by just falling back on a generic interaction type.  The list just indicates the intended or "correct" selections now.

**Comment by maxkfranz** [comment]
> Other than that I would propose to have some icons to represent template types and adding them to the left-most of template interaction lines in the form editor (would have content made up from names of template types e.g. "PM" for protein modification).

I could see how this would be useful for debugging, but I don't see how it adds value for the user.  I would assume that a biologist could correctly interpret what lines like "______ [activates] the [phosphorylation] of ______" mean.

**Comment by maxkfranz** [comment]
> Looks fine to me but putting the form button types in a popover would lead to users having to click twice to create an interaction in comparison to the old way.

I agree.  However, I think that the old way looked confusing in that the buttons didn't look like they belonged to the "add interaction" button.

**Comment by maxkfranz** [comment]
Merging for today's demo

**Comment by sacdallago** [comment]
> https://github.com/PathwayCommons/factoid/pull/332#issuecomment-399598603
This is not a major concern to me. I think it's okay.

> Other than that I would propose to have some icons to represent template types and adding them to the left-most of template interaction lines in the form editor (would have content made up from names of template types e.g. "PM" for protein modification).

What I read as interesting from this is to _draw_ a visual comparison between what the form does and the graph editor. We can discuss tomorrow the details

**Pull request merged**
