### PR TITLE
Iss860 empty submit iss861 irregular org

### PR DESCRIPTION
**Pull request by jvwong**
Add warnings in the submit tooltip:

1. The user has entities (genes/products) that come from >1 organism

Screenshot_2020-10-09 Detection of small vessels for microsurgery by a Doppler flowmeter

2. The user has no elements in their doc

Screenshot_2020-10-09 Detection of small vessels for microsurgery by a Doppler flowmeter (1)

Here, the 'show me help' toggles the help, but I am having trouble understanding how to close the tooltip on clicking the hypertext.

image

Refs #860 and #861

### CODE REVIEW

**Comment by maxkfranz** [comment]
Looks good, but I'd just remove the button rather than disable it.  Invariably, someone's going to try to click the greyed out button anyway.

**Comment by maxkfranz** [comment]
Maybe 'show me how' could be a salient button instead of link.

**Comment by jvwong** [comment]
Do we care about the tooltip closing when the help is open? If not then this one is good to go.

**Comment by maxkfranz** [comment]
Does the submit tooltip stay open after you close the help?  If so, the submit tooltip should be closed on click.

**Comment by jvwong** [comment]
> Does the submit tooltip stay open after you close the help? If so, the submit tooltip should be closed on click.

No everything closes.

**Comment by maxkfranz** [comment]
OK then it’s good to go

**Pull request merged**
