### PR TITLE
Neo4j: Refactoring and Documentation

### PR DESCRIPTION
**Pull request by lindajiawenli**
### Goals:

- [x] Add documentation 
- [x] Move Neo4j tests to main test file
- [x] Move docker-compose.yml and .env files to parent directory
- [x] Declare your local imports using the (relative) path to the actual file (including file extension)

---

Update READ.me to include:
- Neo4j and APOC versions
- configurations and dependencies the Neo4j DB needs to run with factoid
- command for users to run the Neo4j tests

Make sure that a user is able to 
1. Run the Neo4j test suite (Done, see linked issue comment section)
2. Run Neo4j

### CODE REVIEW

**Comment by lindajiawenli** [comment]
The Neo4j config file should contain:

```
dbms.active_database=graph.db
dbms.connector.http.address=0.0.0.0:7474
dbms.connector.bolt.address=0.0.0.0:7687
dbms.security.auth_enabled=false
dbms.directories.data=/path/to/neo4j/data
dbms.directories.plugins=/path/to/neo4j/plugins
apoc.export.file.enabled=true
apoc.import.file.enabled=true
apoc.import.file.use_neo4j_config=true
```

and Neo4j should first be started up from the command line using:
`neo4j start -c /path/to/neo4j/conf/neo4j.conf`

from my understanding (I've been using the docker container that configures all this already, I have yet to test it out myself but I am planning to do it on the 2016 MacBook Air and my Windows 11 laptop)

Guide on config file: https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/

**Comment by jvwong** [comment]
Let's move `src/neo4j/docker-compose.yml` and `.env` out into the parent directory. To me its just the easiest way to document and run these dependencies.

**Comment by lindajiawenli** [comment]
@jvwong I keep getting this warning when I run my Neo4j tests in the main test folder (note: all the tests still pass):
```
(node:88090) Warning: a promise was created in a handler at node:internal/timers:471:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Promise.then (/Users/jiawen/Documents/factoid/node_modules/bluebird/js/release/promise.js:125:17)
(Use `node --trace-warnings ...` to show where the warning was created)
```

I've been combing through my code and I still can't find exactly where the issue is.  

`initDriver`, `closeDriver` and `guaranteeSession` are fine- they don't raise any warnings.
Every function in `neo4j-functions` and `test-functions` does.
Even sample code straight from the Neo4j documentation raises the warning.

Not sure where to go from here

**Comment by jvwong** [comment]
> @jvwong I keep getting this warning when I run my Neo4j tests in the main test folder (note: all the tests still pass):
> 
> ```
> (node:88090) Warning: a promise was created in a handler at node:internal/timers:471:21 but was not returned from it, see http://goo.gl/rRqMUw
>     at Promise.then (/Users/jiawen/Documents/factoid/node_modules/bluebird/js/release/promise.js:125:17)
> (Use `node --trace-warnings ...` to show where the warning was created)
> ```

Can you 
(1) remove your `node_modules`
(2) re-install node modules (v16)
(3) npm run test

Works for me.

**Comment by jvwong** [comment]
I wanted to add an item: Declare your local imports using the (relative) path to the actual file (including file extension).

e.g. replace  `import { createConstraint, addNode, addEdge } from './neo4j-functions';` with
`import { createConstraint, addNode, addEdge } from './neo4j-functions.js';` 


See https://nodejs.org/api/esm.html#import-specifiers

**Comment by maxkfranz** [comment]
> @jvwong I keep getting this warning when I run my Neo4j tests in the main test folder (note: all the tests still pass):
> 
> ```
> (node:88090) Warning: a promise was created in a handler at node:internal/timers:471:21 but was not returned from it, see http://goo.gl/rRqMUw
>     at Promise.then (/Users/jiawen/Documents/factoid/node_modules/bluebird/js/release/promise.js:125:17)
> (Use `node --trace-warnings ...` to show where the warning was created)
> ```
> 
> I've been combing through my code and I still can't find exactly where the issue is.
> 

Like the warning says, you can add `--trace-warnings` to your script in `package.json` to see where the issue originates.  That option might not work with a watch/nodemon, so best to do it with a script that does something like `"foo": "node src/some/dir/foo.js --some-option --trace-warnings"`

**Comment by maxkfranz** [comment]
And as a final note:  That warning usually indicates a potential area for a race condition, which may cause sporadic race conditions and bugs that would be more apparent in low-spec machines or VMs.

**Comment by lindajiawenli** [comment]
> Can you (1) remove your `node_modules` (2) re-install node modules (v16) (3) npm run test
> 
> Works for me.

I tried this, unfortunately I still get the warnings. 
Currently, the tests throwing the errors (basically all the files in `neo4j-test` except  `connect-neo4j.js`) are commented out. 
I'll try a stack trace

**Comment by lindajiawenli** [comment]
I figured out a way to get rid of the warnings! 

The stack trace revealed that my transactions within a given session were being "handled" by their transaction handler (session.executeWrite or session.executeRead), and not explicitly closed with my code (which is why bluebird was giving those warnings).

Relevant Documentation:
[About Transactions](https://neo4j.com/docs/javascript-manual/current/transactions/)
[Official documentation for Sessions](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/session.js~Session.html#instance-method-beginTransaction)
[Official documentation for Transaction Manager](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction-managed.js~ManagedTransaction.html) 
[Official documentation for Transaction Promises](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction-promise.js~TransactionPromise.html)
[Official documentation for Transaction](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction.js~Transaction.html)

### Example Old Code:
```
export async function deleteAllNodesAndEdges() {
    let session;
    try {
        session = guaranteeSession();
        await session.executeWrite(async tx => {
            return await tx.run(deleteAll);
        });
    } catch (error) {
        throw error;
    } finally {
        await session.close();
    }
    return null;
}
```
### Example New Code:
```
export async function deleteAllNodesAndEdges() {
    let session;
    let transaction;
    try {
        session = guaranteeSession();
        transaction = session.beginTransaction();
        await transaction.run(deleteAll);
        await transaction.commit();
    } catch (error) {
        throw error;
    } finally {
        await transaction.close();
        await session.close();
    }
    return null;
}
```

**Comment by lindajiawenli** [comment]
**Pros of making this change:** No more warnings (from what I can see, might discover other bugs later)
**Cons of making this change:** It no longer uses `.executeWrite` and `.executeRead` which in theory could be dangerous, though my functions don't seem to be making accidental writes

Q: Should I make the change in a different branch/PR or keep it all in this PR?
@jvwong

**Comment by jvwong** [comment]
> **Pros of making this change:** No more warnings (from what I can see, might discover other bugs later) **Cons of making this change:** It no longer uses `.executeWrite` and `.executeRead` which in theory could be dangerous, though my functions don't seem to be making accidental writes
> 
> Q: Should I make the change in a different branch/PR or keep it all in this PR? Should I even make the changes? @jvwong

How do you reproduce this error?

**Comment by lindajiawenli** [comment]
1. Switch onto my branch, `iss1174-neo4j-update-readme`
2. For each of the files in `test/neo4j-test/`, uncomment the large block that encompasses basically everything
3. Make sure docker container for neo4j is running
4. `npm run test`

**Comment by jvwong** [comment]
OK I can see the same errors when uncommenting `test/neo4j-test/doc-tests.js` and running the tests on the parent folder.
Any idea why this happening on this branch?

**Comment by lindajiawenli** [comment]
I immediately noticed it when I put all the neo4j tests into the main test
file. I never saw this before (and even now if you use the debugger, there
aren’t any warnings) I moved them.

I suspect that the “bluebird” that is sending these warnings only runs with
the main test file. They are just warnings- the actual tests themselves
pass.

It took me a long time to figure out what was going on, because if you look
at the sample code given in the quick start guides, they use executeWrite
and executeRead and when I pasted them in, it still had warnings. I guess
bluebird wants a very explicit closing of the transaction, session and
driver

**Comment by lindajiawenli** [comment]
I guess another thing we could do is put all the Neo4j tests in a separate folder so it isn't being scanned(?) with bluebird. There won't be any warnings then

**Comment by jvwong** [comment]
> I guess another thing we could do is put all the Neo4j tests in a separate folder so it isn't being scanned(?) with bluebird. There won't be any warnings then

Some breadcrumbs:

- bluebird is a transitive dependency for a bunch of other npm packages
- there is some [unresolved history with neo4j driver and bluebird](https://github.com/neo4j/neo4j-javascript-driver/issues/526)
- the 
- Indeed, in the main test folder, bluebird's `Promse` is configured and imported:

https://github.com/PathwayCommons/factoid/blob/296fce114172f74f5c63e9a1d2dd631a22ee9532/test/util/conf.js#L1-L6

**Comment by jvwong** [comment]
My best guess is that there's some issue with the driver. 

One option is to just disable the bluebird Promise warnings (`Promise.config`) for neo4j test files only.

**Comment by lindajiawenli** [comment]
> My best guess is that there's some issue with the driver.
> 
> One option is to just disable the bluebird Promise warnings (`Promise.config`) for neo4j test files only.

That sounds good! I thought the only options would be:
- disable bluebird for all the tests (which sounds quite risky)
- move the neo4j tests back into their own separate folder (inconvenient) 
- make the changes to my code (I'm hesitant to do this because I've written those functions at the beginning, and changing it now when I'm leaving soon is not ideal).

I would be open to just having bluebird ignore the neo4j tests

**Comment by lindajiawenli** [comment]
>  I'll try a stack trace

Here's the stack trace for reference (in case it becomes relevant in the future)

```
(node:82245) Warning: a promise was created in a handler at node:internal/timers:466:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Promise.then (/Users/jiawen/Documents/factoid/node_modules/bluebird/js/release/promise.js:125:17)
    at finishTransaction (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/transaction.js:461:10)
    at Object.commit (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/transaction.js:301:25)
    at TransactionPromise.Transaction.commit (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/transaction.js:202:37)
    at TransactionExecutor._handleTransactionWorkSuccess (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:155:16)
    at /Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:131:42
From previous event:
    at TransactionExecutor.<anonymous> (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:130:30)
    at step (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:52:23)
    at Object.next (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:33:53)
    at fulfilled (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:24:58)
From previous event:
    at step (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:26:91)
    at /Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:27:9
From previous event:
    at __awaiter (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:23:12)
    at TransactionExecutor._executeTransactionInsidePromise (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:109:16)
    at /Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:76:19
From previous event:
    at TransactionExecutor.execute (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:75:16)
    at Session._executeInTransaction (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/session.js:448:42)
    at Session.executeWrite (/Users/jiawen/Documents/factoid/node_modules/neo4j-driver-core/lib/session.js:437:21)
    at deleteAllNodesAndEdges (/Users/jiawen/Documents/factoid/src/neo4j/neo4j-functions.js:210:23)
    at Context.<anonymous> (/Users/jiawen/Documents/factoid/test/neo4j-test/add-nodes-edges.js:19:11)
    at callFn (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:443:10)
    at /Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:361:14)
    at /Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/jiawen/Documents/factoid/node_modules/mocha/lib/runner.js:339:5)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by lindajiawenli** [comment]
@jvwong I've been looking and I can't seem to find a way to configure bluebird to ignore certain files http://bluebirdjs.com/docs/api/promise.config.html

**Comment by maxkfranz** [comment]
> @jvwong I've been looking and I can't seem to find a way to configure bluebird to ignore certain files http://bluebirdjs.com/docs/api/promise.config.html
> http://bluebirdjs.com/docs/api/environment-variables.html

If it's just a warning, you could turn it off in production so that it doesn't spam up the logs.

I.e. `NODE_ENV === 'production'`

**Comment by maxkfranz** [comment]
I take it back.  It looks like it's just for the tests: https://github.com/PathwayCommons/factoid/blob/f2c00028a5cf4c6fb3f78b75ba39dc3d4ae8d5ca/test/util/conf.js

Perhaps best to just leave it as-is for now, until we're absolutely sure the warning isn't merited.

**Comment by lindajiawenli** [comment]
> I figured out a way to get rid of the warnings!
> 
> The stack trace revealed that my transactions within a given session were being "handled" by their transaction handler (session.executeWrite or session.executeRead), and not explicitly closed with my code (which is why bluebird was giving those warnings).
> 
> Relevant Documentation: [About Transactions](https://neo4j.com/docs/javascript-manual/current/transactions/) [Official documentation for Sessions](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/session.js~Session.html#instance-method-beginTransaction) [Official documentation for Transaction Manager](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction-managed.js~ManagedTransaction.html) [Official documentation for Transaction Promises](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction-promise.js~TransactionPromise.html) [Official documentation for Transaction](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/transaction.js~Transaction.html)
> 
> ### Example Old Code:
> ```
> export async function deleteAllNodesAndEdges() {
>     let session;
>     try {
>         session = guaranteeSession();
>         await session.executeWrite(async tx => {
>             return await tx.run(deleteAll);
>         });
>     } catch (error) {
>         throw error;
>     } finally {
>         await session.close();
>     }
>     return null;
> }
> ```
> 
> ### Example New Code:
> ```
> export async function deleteAllNodesAndEdges() {
>     let session;
>     let transaction;
>     try {
>         session = guaranteeSession();
>         transaction = session.beginTransaction();
>         await transaction.run(deleteAll);
>         await transaction.commit();
>     } catch (error) {
>         throw error;
>     } finally {
>         await transaction.close();
>         await session.close();
>     }
>     return null;
> }
> ```

I have implemented this change across my neo4j functions and as I thought, all the warnings disappear when I do so.

1. Neo4j tests pass without warnings or errors
2. Cron refresh works without issue 
3. Document is added to Neo4j Graph DB on submit without issue.

Shall I push these changes @jvwong @maxkfranz or do we want to keep the `executeWrite`/`executeRead`?

**Comment by maxkfranz** [comment]
Perfect. Go ahead

**Review by jvwong — APPROVED** [review]

**Pull request merged**
