### PR TITLE
Release v0.9.1

### PR DESCRIPTION
**Pull request by jvwong**
- Patches
  - Puppeteer updated their Docker installation instructions
  - Bug in entity BioPAX export template

### CODE REVIEW

**Comment by jvwong** [comment]
I will note that this puppeteer software is temperamental, wouldn't work in Docker (some cy error), then after reboot does works fine.

**Comment by maxkfranz** [comment]
> I will note that this puppeteer software is temperamental, wouldn't work in Docker (some cy error), then after reboot does works fine.

On Mac?

**Comment by jvwong** [comment]
I see this happening from time to  time on the unstable (Ubuntu) and today it happened on Docker (Ubuntu) with the prod instance. It's fine now.

**Comment by jvwong** [comment]
its only at bootup

**Comment by maxkfranz** [comment]
The cluster isn't very fast, and it can't generate anything until the chrome instance has started up (which is heavy).

**Comment by jvwong** [comment]
Oh ok maybe I have to wait a bit.

**Comment by jvwong** [comment]
FYI if you want to 'see' an SBGN of a document: https://apps.pathwaycommons.org/factoids/

**Pull request merged**
