### PR TITLE
Homepage fixes for 0.10.1

### PR DESCRIPTION
**Pull request by maxkfranz**
- Text updates
- Carousel has 20 doc limit & corrected service request
- Updated raf video -- consistent with 'researchers' section
- Visual improvements to carousel
- Better full-screen sizing for above-fold section
- Removes commented-out code

### CODE REVIEW

**Comment by maxkfranz** [comment]
@jvwong, I'm not sure if this is your latest banner.  You may want to drop in a newer version in this branch.

**Review by jvwong — APPROVED** [review]
I dropped in the banner and addded 'SARS-CoV-2' to popup.

**Comment by maxkfranz** [comment]
I think we may have two interactions popups now.  Does that cover both?

**Comment by jvwong** [comment]
> I think we may have two interactions popups now. Does that cover both?

OK missed the second one. I think there's should be a 'Should I use Biofactoid?' sort of popover in the future.

**Pull request merged**
