### PR TITLE
Update document status fields.

### PR DESCRIPTION
**Pull request by jvwong**
- Available status fields, which hopefully are self-evident
  - `INITIATED`
  - `SUBMITTED`
  - `PUBLIC`
  - `TRASHED`

Refs #843

### CODE REVIEW

**Review by maxkfranz — COMMENTED** [review]
Looks good.  Two comments:

(1) Are you planning on converting all the existing documents manually with the new status?  Or should this be handled with an automatic conversion in the code?

(2) The naming of `isPublic()` is a bit inconsistent with the other status methods.  I suppose `public()` and `publicize()` would line up with your other methods, but this isn't very important.

**Comment by jvwong** [comment]
> Looks good. Two comments:
> 
> (1) Are you planning on converting all the existing documents manually with the new status? Or should this be handled with an automatic conversion in the code?

At this point I can migrate this easily with such a simple change. My approach has been to do it 'offline' (local) then load it into an updated instance

> 
> (2) The naming of `isPublic()` is a bit inconsistent with the other status methods. I suppose `public()` and `publicize()` would line up with your other methods, but this isn't very important.

Yeah I just went with the most unambiguous. Didn't feel like `public` sounded like a getter

**Review by maxkfranz — APPROVED** [review]
Fair enough.  Let's just merge it in

**Comment by jvwong** [comment]
I'm gonna clear out the db at some point ...

**Pull request merged**
