### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by d2fong**
- Add consistent branding for both editors
- modularize the 'more' button so both editors can use it as a common component

screen shot 2018-06-22 at 12 36 02 pm
screen shot 2018-06-22 at 12 37 18 pm

### CODE REVIEW

**Comment by d2fong** [comment]
refs #321

**Comment by maxkfranz** [comment]
Merging now.  I have some other tweaks I want to merge in, and I want those to be on top of this PR.  If I notice any minor tweaks needed, I'll just make them in my upcoming PR...

**Comment by maxkfranz** [comment]
@d2fong Take a look at the tweaks branch I'm pushing.  I has some form & network changes.  You may want to take a look to make sure you're not working on the same or conflicting items

**Comment by d2fong** [comment]
Will do.

**Comment by maxkfranz** [comment]
@d2fong I think the form only needs the share link and download bioxpax buttons to be made consistent with the network.  Otherwise, the tweaks branch just needs the model display changes I'm working on now.

**Pull request merged**
