### PR TITLE
Entity related papers

### PR DESCRIPTION
**Pull request by metincansiper**
Refs #742

Handles this issue comment (https://github.com/PathwayCommons/factoid/issues/742#issuecomment-644228132)

### CODE REVIEW

**Comment by jvwong** [comment]
I'm getting an error when it comes to storing the results in doc. Does `doc.get` allow  entity ID as parameter?

https://github.com/PathwayCommons/factoid/blob/c19ade5a75b309fe9ada4d1d87b804c5810099f0/src/server/routes/api/document/index.js#L135

**Comment by jvwong** [comment]
This catch should print out `e.message` 

https://github.com/PathwayCommons/factoid/blob/c19ade5a75b309fe9ada4d1d87b804c5810099f0/src/server/routes/api/document/index.js#L1382

**Comment by metincansiper** [comment]
@jvwong the problems that you mentioned must be solved. Would you review again?

**Comment by metincansiper** [comment]
>Does doc.get allow entity ID as parameter?

Yes I think so. The problem was just because of using the wrong id to search.

**Comment by metincansiper** [comment]
>OK, let’s just merge this in and try it out on unstable. It would be good to address sorting in another PR, and in the meanwhile we can see about the GPU speedup

Okay, I merged it.

**Pull request merged**
