### PR TITLE
Editor submit tweaks

### PR DESCRIPTION
**Pull request by jvwong**
Providing brief thank you, message about user data integration, and more of the thank you email content (links to Explorer view, Tweet, image and share via email).

TaskView panel waits for publish request to complete (i.e. send tweet) before displaying 'done' state.

Ref #703 

Example: Document state is 'published'
Screenshot_2020-04-29 SLC19A1 Is an Importer of the Immunotransmitter cGAMP

Example: Document state is 'submitted' (not published)

Screenshot_2020-04-29 A totally bogus article

### CODE REVIEW

**Comment by gbader** [comment]
Maybe more concise text?
Thank you!
Your paper is now linked to many others and shared for everyone to explore.
[Explore]

(also, not sure what get image or email link do)

**Comment by jvwong** [comment]
> (also, not sure what get image or email link do)

- The 'Get image' opens a new tab showing a PNG image of the network
  - Replace with: 'See image of pathway'?
- The 'Email link' is an HTML anchor using the mailto: URL scheme 
  - Replace with: 'Share via email'?

**Comment by jvwong** [comment]
Update:

image

**Comment by gbader** [comment]
maybe just link to 'twitter' and 'download', since we don't have a lot of space.  Do we need the download? What is the use case?

**Comment by jvwong** [comment]
Screenshot_2020-04-30 miR-1468-3p Promotes Aging-Related Cardiac Fibrosis (2)

**Comment by maxkfranz** [comment]
This may be a good place to reuse the mobile sharing feature.  You could have two buttons in place of the share links:

(1) View @biofactoid tweet
(2) Share my paper

(2) would just reuse the component from #680 to allow for native sharing.

**Comment by maxkfranz** [comment]
Having the native share button also may make printing out the URL in the UI unnecessary.

**Comment by jvwong** [comment]
On desktop:
image

On (share-compatible) mobile:

- tough to test locally
Screenshot_mobile

**Comment by gbader** [comment]
maybe just 'tweet' and 'download'?  users don't need to know the twitter account - again, we have limited space.  Can it be on one line to save space?  Do we need to share generally, or is twitter sufficient?  I'm not sure any scientist is sharing on any medium other than twitter, so I would just start with twitter for now.

**Comment by jvwong** [comment]
image

**Comment by gbader** [comment]
awesome!

**Pull request merged**
