### PR TITLE
Docker configuration updates for NGINX

### PR DESCRIPTION
**Pull request by jvwong**
Forward traffic from internet to NGINX container.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@jvwong, do you want this to be reviewed in depth?  I don't see any red flags.

I'm not assigned to review, so feel free to merge this if you think it's ready.

**Comment by jvwong** [comment]
This is a work in progress. Will be adding to this and testing. 

It will change a bunch...

**Comment by maxkfranz** [comment]
OK, good to know

**Comment by jvwong** [comment]
@maxkfranz I think its time to move the contents of this folder to a new repo for a variety of reasons - something like 'factoid-docker-config' or something.

**Comment by maxkfranz** [comment]
How about a private repo?  That would make deployment easier.

**Comment by jvwong** [comment]
Yeah fair enough. I can make this `https://github.com/PathwayCommons/factoid-docker-config` private.

**Pull request closed without merging**
