### PR TITLE
Updates to docker-compose.

### PR DESCRIPTION
**Pull request by jvwong**
Adding grounding service port and API_KEY env variable.

### CODE REVIEW

**Comment by maxkfranz** [comment]
Does this merit a new tag?

**Comment by jvwong** [comment]
Nah, it's fine for now.

**Comment by maxkfranz** [comment]
Not even 0.5.1?

**Comment by jvwong** [comment]
Sure - actually do it because I want to test whether the Docker Hub picks up the tag...

**Pull request merged**
