### PR TITLE
Automatic grounding of entities (initial version)

### PR DESCRIPTION
**Pull request by maxkfranz**
This revises the UI as per #504 for items (1), (2), and (3).  

The user starts by only typing the name, without anything else to distract him:

Screen Shot 2019-08-16 at 12 48 44 PM

The user types the name of the entity and the best-guess grounding is used by default:

Screen Shot 2019-08-16 at 12 48 51 PM

In all but a small minority of cases, the expected grounding is correct.  If the user does not like the grounding, he can click the button to select a better match:

Screen Shot 2019-08-16 at 12 51 06 PM

If the user types something for which we can't find any possible groundings, we display an error message:

Screen Shot 2019-08-16 at 1 01 36 PM

The UI for complexes is consistent with the automatic grounding UI:

Screen Shot 2019-08-16 at 12 54 46 PM

The UI for interactions is also consistent:

Screen Shot 2019-08-16 at 12 56 58 PM

Related changes:

- Remove support for grouped selection via interaction nodes -- we don't support interaction nodes for n-ary interactions anymore.  Without this change, there are conflicts with automatic grounding.
- Update labels for "entity" to instead use the words "gene or chemical".
- Fix a related selection issue.  When clicking from one node to another node, the old node remains selected.
- Remove the extra spacing for interaction popovers.
- Complexes now have a label, to be consistent with other complete entity nodes.
- Notifications are removed, since they are not relevant with an automatic grounding UI.
- The submission task list excludes complexes and interactions.  They are always submittable.

Ref: 
- Ground a named node by default #504 : (1), (2), and (3) complete
- Remove the grounding popover for complexes #516 : No longer applicable

### CODE REVIEW

**Comment by jvwong** [comment]
- Case 1: auto-ground to top hit
  - Works for me
  - Here, the user is thinking,  "My text name matched the information they displayed (wherever that's from) so i'm done"
- Case 2: 'Select a better match'
  - Do users need to be prompted to actually click something? Should we indicate the grounding that will be applied? 
  - Users are already in the 'autocomplete' mindset.  When their label is not the top hit, they could be thinking  "Hmm like they don't like my name. I need to choose a better one" and you could get the situation below (second hit is the one I want):

image

**Comment by jvwong** [comment]
A related minor point in case 2 is that the 'rank' of an applied ground is always the same. Meaning if I selected one in the middle of the list, then go back and try to ground again, it 'jumps' back into the same rank position.

**Comment by jvwong** [comment]
Minor bleed in interaction tooltip button:

image

**Comment by jvwong** [comment]
Also some bleed on the node tip:

image

**Comment by maxkfranz** [comment]
OK, let's fix those issues in separate PRs.  I'm merging the feature into the unstable branch so it's publicly testable at unstable.factoid.baderlab.org

**Pull request merged**
