### PR TITLE
add a 'tech demo' button where users can look at the technology behin…

### PR DESCRIPTION
**Pull request by d2fong**
…d factoid and choose their editor

screen shot 2018-12-04 at 1 20 14 pm
screen shot 2018-12-04 at 1 20 01 pm

### CODE REVIEW

**Comment by IgorRodchenkov** [comment]
@d2fong 
I merged unstable into this branch (locally).
Trying.. does not work for me. Fails connecting reach (run locally) with or thiout providing REACH_URL before npm run watch... (the lab's reach server is probably down now due to recent storage failure, but I am unsure, and this should not matter normally...)

```
(node:14749) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:28015/api/uploadFile failed, reason: Parse Error
    at ClientRequest.<anonymous> (/home/igor/Workspace/factoid-fork/node_modules/node-fetch/lib/index.js:1369:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnData (_http_client.js:445:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
(node:14749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
error:   Could not fill doc from text: Upon detection of DNA damage, the ATM kinase mediates the phosphorylation of the Mdm2 protein to block its interaction with p53. The p53 protein activates the transcription of cyclin-dependent kinase inhibitor, p21. p21 inactivates the CCNE1:Cdk2 complex.
error:   Exception thrown : request to http://localhost:28015/api/uploadFile failed, reason: Parse Error
info:    POST /api/document 500 37.397 ms - 21
(node:14749) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:28015/api/uploadFile failed, reason: Parse Error
    at ClientRequest.<anonymous> (/home/igor/Workspace/factoid-fork/node_modules/node-fetch/lib/index.js:1369:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnData (_http_client.js:445:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
(node:14749) UnhandledPromise
```

**Comment by d2fong** [comment]
Why should REACH not matter normally?  This purpose of this tech demo is to show REACH specific things.

**Comment by IgorRodchenkov** [comment]
> Why should REACH not matter normally? This purpose of this tech demo is to show REACH specific things.

- I mean, when I define REACH_URL and use local instance... I did not mean that REACH is not needed.

**Comment by d2fong** [comment]
Oh yeah, I misunderstood you.  Yeah thats weird, REACH is working on the unstable factoid site.

**Pull request merged**
