### PR TITLE
Iss753 homepage tweaks text

### PR DESCRIPTION
**Pull request by jvwong**
- Section 'Your pathway to share and explore'
  - Popup info for 'publish and share' 
  - Updated network image
- Contact: Funding sources appended
- Footer: Logos link out to institutions

Refs #753

### CODE REVIEW

**Comment by jvwong** [comment]
- Contact info

image

- Your pathway to share and explore

image

**Comment by maxkfranz** [comment]
Looks good.

The only suggestion I have is around the underlined links.  They can be hard to see in this section:

Screen Shot 2020-06-19 at 12 44 57 PM

Maybe it would be better if the underline were just white for all of those captions.

**Comment by jvwong** [comment]
If you notice, I actually flipped the background image so that it was a bit darker on left.

**Comment by maxkfranz** [comment]
Yeah, I noticed.  The image looks better that way, but I think the blue underline is hard to see in any case

**Pull request merged**
