### PR TITLE
Swagger docs for (Document) web services

### PR DESCRIPTION
**Pull request by jvwong**
- Swagger + UI for the web services (primarily `/api/document/`)
- Access at `/api/api-docs/` 
- GET biopax, sbgn in progress #685

Definitely room to improve later on:
  - Reconcile various PATCH routes
  - More consistent handling of paths and params (i.e. secret)

Refs #698

### CODE REVIEW

**Comment by maxkfranz** [comment]
Looks like there's a problem on prod builds, e.g. http://unstable.factoid.baderlab.org/api/api-docs

**Comment by jvwong** [comment]
It requires the trailing slash: http://unstable.factoid.baderlab.org/api/api-docs/

**Comment by maxkfranz** [comment]
Could we put some simple forwarding routes in place to make it easier if someone types in the URL from the paper?

It would be great if these were supported:

- /api/api-docs : The trailing slash shouldn't make a difference when you type in a URL.  That's the convention, anyway (e.g. `http://biofactoid.org/demo/` is the same as `http://biofactoid.org/demo`).
- /api : Nothing else is going to point here, so we may as well have a shorter address.
- /api/ : The trailing slash should work here too.

**Comment by jvwong** [comment]
what about putting the docs at `/api(/)`?

**Comment by maxkfranz** [comment]
That would be the natural place to put the documentation, if possible.  I thought that the longer `/api/api-docs/` address was used because of some technical conflict with `/api`.

**Comment by jvwong** [comment]
OK I figured it out - I reversed the order of the swagger setup...

**Pull request merged**
