### PR TITLE
Automatic connection of researcher profiles

### PR DESCRIPTION
**Pull request by metincansiper**
Refs  #907

### CODE REVIEW

**Comment by metincansiper** [comment]
I used the paped titled "Race, ethnicity, and NIH research awards." for testing.

**Comment by maxkfranz** [comment]
@metincansiper, looks great.  Could we do the search on the server side when the document is created?  That way the data can be stored and we don't need to make queries to ORCID on each page load.

The data could be stored under the `citation` metadata.  There should already be an entry for the authors in the citation metadata, so the ORCID ID and link could be added under each author entry.

**Comment by metincansiper** [comment]
>@metincansiper, looks great. Could we do the search on the server side when the document is created? That way the data can be stored and we don't need to make queries to ORCID on each page load.

The data could be stored under the citation metadata. There should already be an entry for the authors in the citation metadata, so the ORCID ID and link could be added under each author entry.

@maxkfranz I think putting it under that citation will require making a lot of sync function async. Since there is a high interaction between functions. What do you think?

**Comment by maxkfranz** [comment]
Yes, it definitely makes sense to use async/await for ORCID stuff.

It should probably go just after the Pubmed stuff, since that needs to be loaded before you can query ORCID:

https://github.com/PathwayCommons/factoid/blob/53f40684ffe498b43d8c7a08c613021c5268d40c/src/server/routes/api/document/index.js#L312-L331

Once `fillDocArticle()` has completed, you can read `doc.citation()`.  

It's probably simpler to store your ORCID data separately from `doc.citation()`.  You could use a separate method, like `doc.authorProfiles()`, that returns an array of author info (like `{ name, orcid, etc... }`).  Most of the data for `authorProfiles()` would be the same as `citation().authors`, but you'd also include the ORCID data.

**Comment by metincansiper** [comment]
@maxkfranz I updated the PR as you mentioned.

**Comment by maxkfranz** [comment]
Looks great.  Merged

**Comment by maxkfranz** [comment]
@metincansiper, I noticed a minor issue for old documents.  If a document doesn't have the profiles defined, the summary page throws an error.  Could you use the old Pubmed data as a fallback (without links) if the profiles don't exist?

Thanks

**Comment by metincansiper** [comment]
@maxkfranz I could not figure out the case. I think if ``citation.authors.authorList`` (is this what you mean by the old data?) exists then the ``authorProfiles`` must also exists.

Would you provide an example pmid or document title for me to reproduce?

**Comment by maxkfranz** [comment]
The problem is not document-specific (i.e. PMID).  It happens for documents that were submitted before your change was made.

Those old docs don't have your new data in them, because they were already submitted (i.e. `fillDocArticle()` has already been ran on a previous version of the app).

It should suffice to check whether your new data exists.  If it exists, show the new linked names.  If not, show the old non-clickable names.

**Comment by metincansiper** [comment]
@maxkfranz Okay I created the PR #912

**Pull request merged**
